JUnit5 execution capability
RedMadRobot/gradle-infrastructure pull request #17
Opened 2020-12-01 21:20 UTC by rwqwr

Closes https://github.com/RedMadRobot/gradle-infrastructure/issues/6

2020-12-02 20:03 UTC, osipxd commented
Thank you for your contribution! I'll review it soon

2020-12-03 11:52 UTC, osipxd requested changes
There are some minor comments but looks good overall!
Update this branch to the latest `main` and I'll merge it :)

2020-12-03 11:52 UTC, osipxd commented on src/main/kotlin/Accessors.kt
> +inline fun Project.kotlinTest(crossinline configure: Test.() -> Unit) {
Should be internal

2020-12-03 11:52 UTC, osipxd commented on src/main/kotlin/extension/RedmadrobotExtension.kt
>      val android: AndroidSettings = AndroidSettings()
Rename AndroidSettings to AndroidOptions, please :)
To make it consistent with TestOptions

2020-12-03 11:52 UTC, osipxd commented on src/main/kotlin/extension/RedmadrobotExtension.kt
> +    val testOptions: TestOptions = TestOptions()
Maybe rename it?
```suggestion
    val test: TestOptions = TestOptions()
```

2020-12-03 11:52 UTC, osipxd commented on src/main/kotlin/BaseAndroidPlugin.kt
> +import org.gradle.kotlin.dsl.closureOf
Unused imports here

2020-12-03 11:53 UTC, osipxd commented
It would be good if you add your work e-mail to your GitHub account.

2020-12-07 18:39 UTC, osipxd reviewed
Code is OK. Can you add brief docs about tests configuration to README? To "Usage" section.

2020-12-08 07:37 UTC, rwqwr commented
Yes, I can

2020-12-08 09:51 UTC, osipxd approved these changes

2020-12-08 09:51 UTC, merged

2020-12-08 09:51 UTC, osipxd commented
Thank you for your contribution!